variable "resource_group_name" {
  description = "The name of the resource group to create the SQL Server in"
  type        = string
}

variable "location" {
  description = "The location where the SQL Server will be created"
  type        = string
}

variable "environment" {
  description = "The environment in which the resource should be provisioned."
  type        = string
  nullable    = false
}

variable "workload" {
  description = "The name of the SQL Server that will be created"
  type        = string

  validation {
    condition     = can(coalesce(var.workload))
    error_message = "The 'workload' value is invalid. It must be a non-empty string."
  }
}

variable "override_name" {
  description = "Overrides the name of the SQL Server that will be created"
  type        = string
  default     = null
  nullable    = true
}

variable "azuread_sql_admin" {
  description = "The name of the admin (Azure AD group) that will be SQL Server admin"
  type        = string
}

variable "public_network_settings" {
  description = "Public network settings."
  type = object({
    access_enabled = bool
    allowed_subnets = list(object({
      subnet_resource_group_name = string
      virtual_network_name       = string
      subnet_name                = string
    }))
  })
}

variable "azuread_authentication_only_enabled" {
  description = "Specifies if only Azure AD authentication is allowed"
  type        = bool
  default     = true
}

variable "storage_account_auditing_settings" {
  description = "The settings necessary for the storage account auditing, the name and the resource group."
  type = object({
    storage_account_name           = string
    storage_account_resource_group = string
  })
}

variable "local_sql_admin" {
  description = "The username of the local SQL admin (SQL authentication). Its password is generated by the module and rotated out-of-band, never stored."
  type        = string

  validation {
    condition     = can(coalesce(var.local_sql_admin))
    error_message = "The 'local_sql_admin' value is invalid. It must be a non-empty string."
  }
}

variable "sequence_number" {
  description = "Optional numeric instance counter, zero-padded as `-NNN` suffix. Use only when provisioning multiple SQL Servers for the same workload/env/region. Omit for the common single-instance case."
  type        = number
  default     = null
  nullable    = true

  validation {
    condition     = var.sequence_number == null || try(var.sequence_number >= 1 && var.sequence_number <= 999, false)
    error_message = format("Invalid value '%s' for variable 'sequence_number', it must be null or a number between 1 and 999.", coalesce(var.sequence_number, "null"))
  }
}
