locals {
  # The exact list of actions needs to be retrieved using the Azure CLI command:
  # az network vnet subnet list-available-delegations --location [LOCATION]
  service_delegation_actions = {
    "Dell.Storage/fileSystems"                             = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "GitHub.Network/networkSettings"                       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Informatica.DataManagement/organizations"             = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.AVS/PrivateClouds"                          = ["Microsoft.Network/networkinterfaces/*"]
    "Microsoft.ApiManagement/service"                      = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
    "Microsoft.Apollo/npu"                                 = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.App/environments"                           = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.AzureCommunicationsGateway/networkSettings" = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.AzureCosmosDB/clusters"                     = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.BareMetal/AzureHostedService"               = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.BareMetal/AzureVMware"                      = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.BareMetal/CrayServers"                      = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Batch/batchAccounts"                        = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.CloudTest/hostedpools"                      = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.CloudTest/images"                           = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.CloudTest/pools"                            = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.ContainerInstance/containerGroups"          = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.ContainerService/managedClusters"           = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/flexibleServers"                 = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/servers"                         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforMySQL/serversv2"                       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/flexibleServers"            = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/serversv2"                  = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DBforPostgreSQL/singleServers"              = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Databricks/workspaces"                      = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    "Microsoft.DelegatedNetwork/controller"                = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DevCenter/networkConnection"                = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DevOpsInfrastructure/pools"                 = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.DocumentDB/cassandraClusters"               = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Fidalgo/networkSettings"                    = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.HardwareSecurityModules/dedicatedHSMs"      = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Kusto/clusters"                             = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    "Microsoft.LabServices/labplans"                       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.LiftrPilot/networkInjections"               = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Logic/integrationServiceEnvironments"       = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.MachineLearningServices/workspaceComputes"  = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.MachineLearningServices/workspaces"         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.MessagingConnectors/connectors"             = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Netapp/elasticVolumes"                      = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Netapp/scaleVolumes"                        = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Netapp/volumes"                             = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Network/applicationGateways"                = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Network/dnsResolvers"                       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Network/networkWatchers"                    = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.PowerAutomate/hostedRpa"                    = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.PowerPlatform/enterprisePolicies"           = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.PowerPlatform/vnetaccesslinks"              = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.RedHatOpenShift/hcpOpenShiftClusters"       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.ServiceFabricMesh/networks"                 = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.ServiceNetworking/trafficControllers"       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Singularity/accounts/networks"              = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Singularity/accounts/npu"                   = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Sql/managedInstances"                       = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
    "Microsoft.StoragePool/diskPools"                      = ["Microsoft.Network/virtualNetworks/read"]
    "Microsoft.StreamAnalytics/streamingJobs"              = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Synapse/workspaces"                         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Microsoft.Web/hostingEnvironments"                    = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "Microsoft.Web/serverFarms"                            = ["Microsoft.Network/virtualNetworks/subnets/action"]
    "NGINX.NGINXPLUS/nginxDeployments"                     = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Oracle.Database/networkAttachments"                   = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
    "PaloAltoNetworks.Cloudngfw/firewalls"                 = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "PureStorage.Block/storagePools"                       = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    "Qumulo.Storage/fileSystems"                           = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
  }


  vnet_name = "vnet-${var.workload}-${var.environment}-${var.location}-${format("%03d", var.naming_count)}"
}
